### ISSUE TITLE
Writing emails to the placement officers from colleges of Kerala.

### ISSUE THREAD

**Issue by DeepakPalaksha** [junoyu12/callus-aiimstec#26]
Writing emails to the placement officers from colleges of Kerala.

DOD:
Emails sent to all the placement officer in the excel sheet.

**Comment by mohanhc** [comment]
Email sent to Placement officers, total data was provided 486 sent to all 486 recipients .

**Comment by mohanhc** [comment]
sent to individual placement officers email id.
